name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: [self-hosted]
    steps:
      - run: pwd
      - run: ls -lah
      - uses: actions/checkout@v3
        with:
          ref: main
      - run: kubectl apply -f config/workload.yaml
      - run: tanzu apps workload get tanzu-java-web-app
      - run: sleep 15
      - run: kp build logs tanzu-java-web-app
