name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: [self-hosted]
    steps:
      - run: pwd
      - run: ls -lah
      - uses: actions/checkout@v3
        with:
          ref: main
      - run: ls -lah 
