name: learn-github-actions
on: [push]
jobs:
  Build-And-Deploy:
    runs-on: [self-hosted]
    steps:
      - run: echo "Running Build"
      - uses: actions/checkout@v3
        with:
          ref: main
      - run: kubectl apply -f config/workload.yaml
      - run: tanzu apps workload get tanzu-java-web-app
      - run: sleep 29
      - run: kp build logs tanzu-java-web-app
